# Generated by Django 5.0.3 on 2024-03-12 09:28

import django_resized.forms
import webapps2024.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "🇺🇸 US Dollars"),
                    ("EUR", "🇪🇺 Euros"),
                    ("JPY", "🇯🇵 Yen"),
                    ("CNY", "🇨🇳 Chinese Yuan"),
                    ("INR", "🇮🇳 Rupee"),
                    ("GBP", "🇬🇧 Pounds"),
                    ("CAD", "🇨🇦 Canadian Dollars"),
                    ("BTC", "🔒 Bitcoin"),
                    ("ETH", "🧬 Ethereum"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                default="images/default.png",
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[300, 300],
                upload_to=webapps2024.utils.media.MediaHelper,
            ),
        ),
    ]
