# Generated by Django 5.0.3 on 2024-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineaccount",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
