# Generated by Django 5.0.3 on 2024-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "🇺🇸 US Dollars"),
                    ("EUR", "🇪🇺 Euros"),
                    ("GBP", "🇬🇧 Pounds"),
                ],
                max_length=3,
            ),
        ),
    ]
