# Generated by Django 5.0.3 on 2024-03-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_alter_onlineaccount_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlineaccount",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
