# Generated by Django 5.0.3 on 2024-04-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_alter_onlineaccount_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="routing_number",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="pin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
