# Generated by Django 5.0.3 on 2024-03-12 13:43

import django_resized.forms
import uuid
import webapps2024.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_rename_paypal_account_userprofile_payapp_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="payapp_account",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[300, 300],
                upload_to=webapps2024.utils.media.MediaHelper,
            ),
        ),
    ]
