# Generated by Django 5.0.3 on 2024-03-12 14:00

import django_resized.forms
import webapps2024.utils.media
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                default="images/default.png",
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[300, 300],
                upload_to=webapps2024.utils.media.MediaHelper.get_image_upload_path,
            ),
        ),
    ]
