# Generated by Django 5.0.3 on 2024-03-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0007_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
