# Generated by Django 5.0.3 on 2024-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0008_bankaccount_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("BANK_OF_AMERICA", "Bank of America"),
                    ("CHINA_UNION_PAY", "China Union Pay"),
                    ("CREDIT_AGRICOLE", "Credit Agricole"),
                    ("CREDIT_SUISSE", "Credit Suisse"),
                    ("DEUTSCHE_BANK", "Deutsche Bank"),
                    ("JPMORGAN_CHASE", "JPMorgan Chase"),
                    ("MASTERCARD", "Mastercard"),
                    ("ACCESS_BANK", "Access Bank"),
                    ("FIRST_BANK", "First Bank of Nigeria"),
                    ("GTBANK", "Guaranty Trust Bank"),
                    ("ZENITH_BANK", "Zenith Bank"),
                    ("UBA", "United Bank for Africa"),
                    ("STANBIC_IBTC", "Stanbic IBTC Bank"),
                ],
                default="ACCESS_BANK",
                max_length=50,
            ),
        ),
    ]
