# Generated by Django 5.0.3 on 2024-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyconversion",
            name="currency_from",
            field=models.CharField(
                choices=[
                    ("USD", "🇺🇸 US Dollars"),
                    ("EUR", "🇪🇺 Euros"),
                    ("GBP", "🇬🇧 Pounds"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="currencyconversion",
            name="currency_to",
            field=models.CharField(
                choices=[
                    ("USD", "🇺🇸 US Dollars"),
                    ("EUR", "🇪🇺 Euros"),
                    ("GBP", "🇬🇧 Pounds"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "🇺🇸 US Dollars"),
                    ("EUR", "🇪🇺 Euros"),
                    ("GBP", "🇬🇧 Pounds"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
