# Generated by Django 5.0.3 on 2024-03-14 03:03

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0003_transactionhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionhistory",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelManagers(
            name="transactionhistory",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="transactionhistory",
            name="date",
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
